import { Prisma } from '@prisma/client';
import { prisma } from '../src/prisma.js';

const email = process.env.SEED_USER_EMAIL?.trim().toLowerCase() || 'waghmare.sachin1994@gmail.com';
const profileData = { firstName: 'Sachin', lastName: 'Waghmare', headline: 'Senior Frontend Engineer', location: 'Pune, Maharashtra, India', website: 'https://linkedin.com/in/sachin-waghmare', yearsOfExperience: 10, summary: 'Senior Frontend Engineer with 10+ years architecting and modernizing enterprise-scale web applications across banking, regulatory reporting, and logistics domains. Deep expertise in React, Angular, TypeScript, and micro-frontend architecture, with experience leading platform modernization and setting frontend engineering standards under strict regulatory timelines. AI-first development experience using GitHub Copilot, Claude, and Devin across the development lifecycle.', targetRoles: ['Senior Frontend Engineer', 'Frontend Architect', 'Staff Frontend Engineer'], preferredLocations: ['Pune', 'Remote'], remotePreference: 'flexible' };
const skills = ['React', 'Angular', 'Next.js', 'TypeScript', 'JavaScript ES6+', 'HTML5', 'CSS3', 'SCSS', 'Tailwind CSS', 'Material UI', 'AG Grid', 'Redux Toolkit', 'NgRx', 'RxJS', 'React Query / TanStack Query', 'Micro Frontends', 'Webpack Module Federation', 'Component Libraries', 'Design Systems', 'Performance Optimization', 'Accessibility / WCAG', 'Code Splitting', 'Lazy Loading', 'Node.js', 'Express', 'REST APIs', 'Java', 'PostgreSQL', 'Prisma ORM', 'SQL', 'Jest', 'React Testing Library', 'Cypress', 'Playwright', 'Jasmine', 'Karma', 'GitHub Copilot', 'Claude', 'Devin', 'LLM concepts', 'RAG-based integrations', 'Docker', 'GitHub Actions', 'CI/CD', 'Git', 'Webpack', 'GHCR', 'ESLint', 'Prettier', 'SonarQube'];
const experiences = [
  { title: 'Senior Frontend Engineer (Information Officer)', company: 'Citicorp India', startDate: '2023-02-01', endDate: null, description: 'Leads frontend engineering for enterprise regulatory reporting platforms supporting compliance workflows across global banking operations. Drove adoption of AI-first development practices using GitHub Copilot, Claude and Devin; led modernization into modular Angular architecture; architected reusable components, shared services and validation frameworks; designed complex accessible compliance workflows; built resilient REST API integration layers; improved performance through modular architecture, lazy loading, optimized change detection and efficient rendering; partnered with Product, Compliance, UX, QA and Backend teams.' },
  { title: 'Frontend Engineer', company: 'BBD Software India', startDate: '2019-12-01', endDate: '2023-02-01', description: 'Built enterprise banking applications supporting customer onboarding, device-upgrade journeys and internal banking operations. Developed scalable Angular applications using NgRx and RxJS; delivered digital customer eligibility and device-upgrade platforms; built reusable UI components and shared services; integrated REST APIs with robust client-side validation; contributed to Agile delivery, sprint planning, code reviews and CI/CD.' },
  { title: 'Software Developer', company: 'INIQUUS IT Services', startDate: '2017-12-01', endDate: '2019-12-01', description: 'Built web-based platforms for logistics operations and investor account management. Developed client-order auto-matching workflows, investor dashboards for portfolio and SIP insights, complex form validation, and UI features using Angular, Redux, TypeScript, JavaScript, HTML and SCSS.' },
  { title: 'Software Developer', company: 'Network Components', startDate: '2016-10-01', endDate: '2017-11-01', description: 'Built internal web applications for IT workflows, project tracking and approval processes. Refactored legacy JavaScript codebases, implemented dashboards for project and ticket visibility, and developed UI components using Angular, Redux, TypeScript, JavaScript, HTML and SCSS.' },
];
const education = [{ institution: 'Government Engineering College, North Maharashtra University, Jalgaon', degree: 'Bachelor of Engineering', field: 'Computer Engineering — CGPA 8.34', startDate: '2012-07-01', endDate: '2016-06-01' }, { institution: 'Government Polytechnic, Solapur', degree: 'Diploma', field: 'Computer Technology — Percentage 80.35%', startDate: '2009-07-01', endDate: '2012-06-01' }];
const projects = [{ name: 'Nexus — Microfrontend Platform', description: 'Personal / Open Source. Architected a microfrontend platform using Webpack 5 Module Federation with four independent React 18 micro-apps, Docker multi-stage builds, docker-compose orchestration and GitHub Actions CI/CD deploying to GHCR. Technologies: React, Webpack 5, Module Federation, Docker, Docker Compose, GitHub Actions, GHCR.' }, { name: 'Local Clothing Store Web App', description: 'In development. Full-stack e-commerce platform using Next.js 14, PostgreSQL, Prisma ORM, NextAuth.js and Razorpay, covering product catalog, cart, authentication and payment workflows. Technologies: Next.js, PostgreSQL, Prisma, NextAuth.js, Razorpay.' }];
const pillars = ['Frontend Architecture', 'React & Angular', 'AI-Assisted Software Development', 'Micro Frontends', 'Engineering Productivity', 'Enterprise Frontend Engineering', 'Career & Interview Insights'];
const content = (profileId: string, ids: { experiences: string[]; educations: string[]; skills: string[]; projects: string[] }) => ({ summary: profileData.summary, sectionOrder: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'achievements'], visibleSections: { summary: true, experience: true, education: true, skills: true, projects: true, certifications: true, achievements: true }, experienceIds: ids.experiences, educationIds: ids.educations, skillIds: ids.skills, projectIds: ids.projects, certificationIds: [], achievementIds: [], acceptedSuggestionIds: [], profileId });
async function main() {
  const user = await prisma.user.upsert({ where: { email }, update: {}, create: { email } });
  const profile = await prisma.profile.upsert({ where: { userId: user.id }, update: {}, create: { userId: user.id, ...profileData } });
  const experienceIds: string[] = []; for (const item of experiences) { const existing = await prisma.experience.findFirst({ where: { profileId: profile.id, company: item.company, title: item.title } }); const record = existing ?? await prisma.experience.create({ data: { profileId: profile.id, ...item, startDate: new Date(item.startDate), endDate: item.endDate ? new Date(item.endDate) : null } }); experienceIds.push(record.id); }
  const educationIds: string[] = []; for (const item of education) { const existing = await prisma.education.findFirst({ where: { profileId: profile.id, institution: item.institution, degree: item.degree } }); const record = existing ?? await prisma.education.create({ data: { profileId: profile.id, ...item, startDate: new Date(item.startDate), endDate: new Date(item.endDate) } }); educationIds.push(record.id); }
  const skillIds: string[] = []; for (const name of skills) { const existing = await prisma.skill.findFirst({ where: { profileId: profile.id, name } }); const record = existing ?? await prisma.skill.create({ data: { profileId: profile.id, name, technology: true } }); skillIds.push(record.id); }
  const projectIds: string[] = []; for (const item of projects) { const existing = await prisma.project.findFirst({ where: { profileId: profile.id, name: item.name } }); const record = existing ?? await prisma.project.create({ data: { profileId: profile.id, ...item } }); projectIds.push(record.id); }
  const resume = await prisma.resume.findFirst({ where: { userId: user.id, title: 'Senior Frontend Engineer — Master Resume' }, include: { versions: { orderBy: { version: 'desc' }, take: 1 } } });
  if (!resume) await prisma.resume.create({ data: { userId: user.id, title: 'Senior Frontend Engineer — Master Resume', versions: { create: { version: 1, content: content(profile.id, { experiences: experienceIds, educations: educationIds, skills: skillIds, projects: projectIds }) as Prisma.InputJsonValue } } } });
  await prisma.contentStrategy.upsert({ where: { userId: user.id }, update: {}, create: { userId: user.id, targetAudience: 'Frontend Engineers, Senior Engineers, Engineering Managers, Tech Leads, Software Architects', writingVoice: 'Practical, technical, concise, experience-driven, educational and professional.', postingFrequency: 'Weekly', recurringThemes: ['Frontend Architecture', 'React & Angular', 'AI-Assisted Software Development', 'Micro Frontends', 'Engineering Productivity', 'Enterprise Frontend Engineering', 'Career & Interview Insights'] } });
  for (const name of pillars) { const existing = await prisma.contentPillar.findFirst({ where: { userId: user.id, name } }); if (!existing) await prisma.contentPillar.create({ data: { userId: user.id, name, description: 'Seeded from the supplied professional resume.' } }); }
  console.log(`Seeded profile for ${email}: ${experienceIds.length} experiences, ${educationIds.length} education records, ${skillIds.length} skills, ${projectIds.length} projects.`);
}
main().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { await prisma.$disconnect(); });
