import type { ReactNode } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Alert, Box, Button, Card, CardContent, Chip, Grid, Stack, Typography } from '@mui/material';
import { ArrowUpRight, CalendarDays, FileEdit, Lightbulb, Sparkles } from 'lucide-react';
import { getHealth } from './lib/api';
import { EmptyState } from './components/EmptyState';
const pageCopy = { Profile: ['Your professional profile', 'Keep your experience, skills, projects and goals in one place.', 'Add your first profile details'], Resume: ['Resume builder', 'Create tailored resume versions from the profile you control.', 'Create a resume'], Jobs: ['Job search', 'Collect and evaluate opportunities that match the direction you want to take.', 'Add a job'], Applications: ['Application tracker', 'See every application, next step and follow-up in one calm workspace.', 'Track an application'], Settings: ['Settings', 'Manage your preferences, data and integrations.', undefined] } as const;
export function Dashboard() { const health = useQuery({ queryKey: ['health'], queryFn: getHealth, retry: false }); return <Stack spacing={4}><Box><Typography variant="overline" color="primary" sx={{ fontWeight: 800, letterSpacing: '.14em' }}>Monday, let’s make progress</Typography><Typography variant="h1" sx={{ mt: .5 }}>Good to have you here.</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Your professional operating system starts with a clear foundation.</Typography></Box><Grid container spacing={2}><Metric icon={<Sparkles size={18} />} label="Profile completeness" value="—" detail="Add your profile to get started" color="primary" /><Metric icon={<FileEdit size={18} />} label="Active drafts" value="—" detail="Your next post will live here" color="secondary" /><Metric icon={<CalendarDays size={18} />} label="Upcoming follow-ups" value="—" detail="Nothing scheduled" color="warning" /></Grid><Grid container spacing={2.5}><Grid size={{ xs: 12, md: 7 }}><Card sx={{ height: '100%' }}><CardContent sx={{ p: 3 }}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'flex-start' }}><Box><Typography variant="h2">Make your next move</Typography><Typography color="text.secondary" sx={{ mt: .75 }}>A few focused actions will unlock the rest of your workspace.</Typography></Box><Chip label="Getting started" color="primary" variant="outlined" /></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} sx={{ mt: 3 }}><Button variant="contained" endIcon={<ArrowUpRight size={16} />}>Set up profile</Button><Button variant="outlined" startIcon={<Lightbulb size={16} />}>Capture an idea</Button></Stack></CardContent></Card></Grid><Grid size={{ xs: 12, md: 5 }}><Card sx={{ height: '100%' }}><CardContent sx={{ p: 3 }}><Typography variant="h3">Workspace status</Typography><Alert severity={health.isError ? 'warning' : 'success'} sx={{ mt: 2 }}>{health.isPending ? 'Checking API…' : health.isError ? 'API unavailable' : 'All systems operational'}</Alert><Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>Your data stays grounded in the information you choose to add.</Typography></CardContent></Card></Grid></Grid></Stack>; }
function Metric({ icon, label, value, detail, color }: { icon: ReactNode; label: string; value: string; detail: string; color: 'primary' | 'secondary' | 'warning' }) { return <Grid size={{ xs: 12, md: 4 }}><Card><CardContent sx={{ p: 2.5 }}><Stack direction="row" sx={{ justifyContent: 'space-between' }}><Typography variant="body2" color="text.secondary">{label}</Typography><Box sx={{ color: `${color}.main`, display: 'flex' }}>{icon}</Box></Stack><Typography sx={{ mt: 2, fontSize: 32, fontWeight: 800, letterSpacing: '-.04em' }}>{value}</Typography><Typography variant="caption" color="text.secondary">{detail}</Typography></CardContent></Card></Grid>; }
export function Placeholder({ name }: { name: keyof typeof pageCopy }) { const [title, description, action] = pageCopy[name]; return <Stack spacing={3}><PageHeading title={title} description={description} /><EmptyState title={`${name} is ready for your data`} description="This area is intentionally empty until you add your own information. We will never invent jobs, companies, qualifications or career history." action={action} /></Stack>; }
function PageHeading({ title, description }: { title:string; description:string }) { return <Box><Typography variant="h1">{title}</Typography><Typography color="text.secondary" sx={{ mt: 1, maxWidth: 680 }}>{description}</Typography></Box>; }
