import { NavLink, Outlet } from 'react-router-dom';
import { Bot, BriefcaseBusiness, CreditCard, FileText, Kanban, LayoutDashboard, Menu, MessageCircleQuestion, PackageCheck, PenLine, Settings, UserRound, X } from 'lucide-react';
import { useState } from 'react';
import { navigationItems } from '@pba/shared';

const icons = { 'layout-dashboard': LayoutDashboard, 'user-round': UserRound, 'file-text': FileText, 'briefcase-business': BriefcaseBusiness, kanban: Kanban, 'package-check': PackageCheck, 'message-circle-question': MessageCircleQuestion, bot: Bot, 'pen-line': PenLine, 'credit-card': CreditCard, settings: Settings };
export function Layout() {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen lg:flex"><aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-20 w-72 border-r border-slate-200 bg-white p-5 transition-transform lg:static lg:translate-x-0`}><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-600">PBA</p><p className="mt-1 text-lg font-bold">Personal Brand Assistant</p></div><button aria-label="Close navigation" className="lg:hidden" onClick={() => setOpen(false)}><X size={20}/></button></div><nav className="mt-10 space-y-1" aria-label="Primary navigation">{navigationItems.map(item => { const Icon = icons[item.icon]; return <NavLink key={item.path} to={item.path} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${isActive ? 'bg-indigo-50 text-indigo-700' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-950'}`}><Icon size={18}/>{item.label}</NavLink>; })}</nav><div className="absolute bottom-6 left-5 right-5 rounded-xl bg-slate-50 p-4"><p className="text-sm font-semibold">Build your career system</p><p className="muted mt-1">Start with your profile to unlock the rest of your workspace.</p></div></aside><main className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-5 lg:px-10"><button aria-label="Open navigation" className="lg:hidden" onClick={() => setOpen(true)}><Menu size={22}/></button><span className="text-sm font-medium text-slate-500">Workspace</span><div className="h-8 w-8 rounded-full bg-indigo-100 text-center text-sm font-bold leading-8 text-indigo-700">?</div></header><div className="p-5 lg:p-10"><Outlet /></div></main></div>;
}
