import { useState } from 'react';
import { NavLink, Outlet } from 'react-router-dom';
import { AppBar, Avatar, Box, Drawer, IconButton, List, ListItemButton, ListItemIcon, ListItemText, Toolbar, Tooltip, Typography } from '@mui/material';
import { Menu, X } from 'lucide-react';
import { navigationItems } from '@pba/shared';
import { icons } from './navigationIcons';
const drawerWidth = 264;
export function Layout() {
  const [open, setOpen] = useState(false);
  const navigation = <Box sx={{ px: 1.5, py: 2 }}><Box sx={{ px: 1.5, mb: 3 }}><Typography variant="overline" color="primary" sx={{ fontWeight: 800, letterSpacing: '.18em' }}>PBA</Typography><Typography sx={{ fontWeight: 800, lineHeight: 1.2 }}>Personal Brand<br />Assistant</Typography></Box><List component="nav" aria-label="Primary navigation" sx={{ display: 'grid', gap: .5 }}>{navigationItems.map(item => { const Icon = icons[item.icon]; return <ListItemButton key={item.path} component={NavLink} to={item.path} onClick={() => setOpen(false)} sx={{ borderRadius: 2, color: 'text.secondary', '&.active': { bgcolor: 'primary.light', color: 'primary.dark', '& .MuiListItemIcon-root': { color: 'primary.main' } } }}><ListItemIcon sx={{ minWidth: 36, color: 'inherit' }}><Icon size={18} /></ListItemIcon><ListItemText primary={item.label} slotProps={{ primary: { sx: { fontSize: 13, fontWeight: 650 } } }} /></ListItemButton>; })}</List><Box sx={{ mt: 3, mx: 1, p: 2, borderRadius: 2.5, bgcolor: 'secondary.light' }}><Typography variant="body2" sx={{ fontWeight: 750 }}>Build your career system</Typography><Typography variant="caption" color="text.secondary">Start with your profile to unlock the workspace.</Typography></Box></Box>;
  return <Box sx={{ minHeight: '100vh', display: 'flex' }}><AppBar position="fixed" color="inherit" sx={{ display: { xs: 'flex', lg: 'none' }, zIndex: theme => theme.zIndex.drawer + 1, borderBottom: 1, borderColor: 'divider' }}><Toolbar><IconButton onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20} /></IconButton><Typography sx={{ ml: 1, fontWeight: 800 }}>Personal Brand Assistant</Typography></Toolbar></AppBar><Drawer variant="temporary" open={open} onClose={() => setOpen(false)} ModalProps={{ keepMounted: true }} sx={{ display: { xs: 'block', lg: 'none' }, '& .MuiDrawer-paper': { width: drawerWidth } }}><Box sx={{ display: 'flex', justifyContent: 'flex-end', p: 1 }}><IconButton onClick={() => setOpen(false)} aria-label="Close navigation"><X size={20} /></IconButton></Box>{navigation}</Drawer><Drawer variant="permanent" sx={{ display: { xs: 'none', lg: 'block' }, width: drawerWidth, flexShrink: 0, '& .MuiDrawer-paper': { width: drawerWidth, boxSizing: 'border-box' } }}>{navigation}</Drawer><Box component="main" sx={{ flex: 1, minWidth: 0 }}><AppBar position="static" color="inherit" sx={{ display: { xs: 'none', lg: 'block' }, borderBottom: 1, borderColor: 'divider' }}><Toolbar sx={{ justifyContent: 'space-between', px: { lg: 4 } }}><Box><Typography variant="body2" color="text.secondary">Workspace</Typography><Typography sx={{ fontWeight: 750 }}>Your professional command center</Typography></Box><Tooltip title="Account"><Avatar sx={{ width: 34, height: 34, bgcolor: 'primary.light', color: 'primary.dark', fontSize: 14, fontWeight: 800 }}>?</Avatar></Tooltip></Toolbar></AppBar><Box sx={{ p: { xs: 2, sm: 3, lg: 5 }, pt: { xs: 10, lg: 5 }, maxWidth: 1500, mx: 'auto' }}><Outlet /></Box></Box></Box>;
}
