import { applicationCreateSchema, applicationStatusSchema, applicationUpdateSchema } from '@pba/shared';
import { prisma } from './prisma.js';
import { JobNotFoundError } from './jobService.js';

export class ApplicationNotFoundError extends Error { constructor() { super('Application not found'); this.name = 'ApplicationNotFoundError'; } }
const include = { job: { include: { savedJob: true } }, resumeVersion: { include: { resume: true } }, coverLetters: { orderBy: { createdAt: 'desc' as const } }, statusHistory: { orderBy: { changedAt: 'asc' as const } }, interviews: true, followUps: true } as const;
async function owned(userId: string, id: string) { const application = await prisma.application.findFirst({ where: { id, userId }, include }); if (!application) throw new ApplicationNotFoundError(); return application; }
function date(value: string | null | undefined) { return value ? new Date(value) : null; }
export async function listApplications(userId: string, filters: { search?: string | undefined; status?: string | undefined }) { const search = filters.search?.trim(); return prisma.application.findMany({ where: { userId, ...(filters.status ? { status: filters.status } : {}), ...(search ? { job: { OR: [{ title: { contains: search, mode: 'insensitive' } }, { company: { contains: search, mode: 'insensitive' } }] } } : {}) }, orderBy: { updatedAt: 'desc' }, include }); }
export async function getApplication(userId: string, id: string) { return owned(userId, id); }
async function verifyReferences(userId: string, jobId: string, resumeVersionId: string | null) { const job = await prisma.job.findFirst({ where: { id: jobId, userId }, select: { id: true } }); if (!job) throw new JobNotFoundError(); if (resumeVersionId) { const resume = await prisma.resumeVersion.findFirst({ where: { id: resumeVersionId, resume: { userId } }, select: { id: true } }); if (!resume) throw new JobNotFoundError(); } }
export async function createApplication(userId: string, input: unknown) { const value = applicationCreateSchema.parse(input); await verifyReferences(userId, value.jobId, value.resumeVersionId); const application = await prisma.application.create({ data: { userId, jobId: value.jobId, status: value.status, appliedAt: date(value.appliedAt), resumeVersionId: value.resumeVersionId, notes: value.notes, interviewDate: date(value.interviewDate), followUpDate: date(value.followUpDate), statusHistory: { create: { toStatus: value.status } }, ...(value.coverLetter ? { coverLetters: { create: { content: value.coverLetter, userId } } } : {}) }, include }); return application; }
export async function updateApplication(userId: string, id: string, input: unknown) { const existing = await owned(userId, id); const value = applicationUpdateSchema.parse(input); if (value.jobId || value.resumeVersionId) await verifyReferences(userId, value.jobId ?? existing.jobId, value.resumeVersionId ?? existing.resumeVersionId); const data = { ...(value.jobId ? { jobId: value.jobId } : {}), ...(value.status ? { status: value.status } : {}), ...(value.appliedAt !== undefined ? { appliedAt: date(value.appliedAt) } : {}), ...(value.resumeVersionId !== undefined ? { resumeVersionId: value.resumeVersionId } : {}), ...(value.notes !== undefined ? { notes: value.notes } : {}), ...(value.interviewDate !== undefined ? { interviewDate: date(value.interviewDate) } : {}), ...(value.followUpDate !== undefined ? { followUpDate: date(value.followUpDate) } : {}) }; const operations = [prisma.application.update({ where: { id }, data, include })]; if (value.status && value.status !== existing.status) operations.push(prisma.applicationStatusHistory.create({ data: { applicationId: id, fromStatus: existing.status, toStatus: value.status } }) as never); if (value.coverLetter) operations.push(prisma.coverLetter.create({ data: { applicationId: id, content: value.coverLetter, userId } }) as never); await prisma.$transaction(operations); return owned(userId, id); }
export async function deleteApplication(userId: string, id: string) { await owned(userId, id); await prisma.application.delete({ where: { id } }); }
export const validApplicationStatus = (value: unknown) => applicationStatusSchema.parse(value);
