import { contentDraftCreateSchema, contentDraftUpdateSchema, contentGenerationRequestSchema, contentIdeaSchema, contentStrategySchema, contentTransformSchema, type ContentStatus } from '@pba/shared';
import { z } from 'zod';
import type { Prisma } from '@prisma/client';
import { createPublishingProvider } from './contentPublishingProvider.js';
import { prisma } from './prisma.js';
import { createContentProvider, type ContentFact } from './aiContentProvider.js';

export class ContentNotFoundError extends Error { constructor() { super('Content item not found'); this.name = 'ContentNotFoundError'; } }
export class InvalidContentTransitionError extends Error { constructor(message: string) { super(message); this.name = 'InvalidContentTransitionError'; } }
const include = { revisions: { orderBy: { version: 'desc' as const } }, critiques: { orderBy: { createdAt: 'desc' as const } } };
async function facts(userId: string): Promise<ContentFact[]> { const p = await prisma.profile.findUnique({ where: { userId }, include: { experiences: true, educations: true, skills: true, projects: true, certifications: true, achievements: true } }); if (!p) return []; return [...p.experiences.map(x => ({ id: x.id, text: `${x.title} at ${x.company}. ${x.description ?? ''}` })), ...p.educations.map(x => ({ id: x.id, text: `${x.degree} ${x.field ?? ''} at ${x.institution}` })), ...p.skills.map(x => ({ id: x.id, text: x.name })), ...p.projects.map(x => ({ id: x.id, text: `${x.name}. ${x.description ?? ''}` })), ...p.certifications.map(x => ({ id: x.id, text: `${x.name} ${x.issuer ?? ''}` })), ...p.achievements.map(x => ({ id: x.id, text: `${x.title}. ${x.description ?? ''}` }))]; }
type DraftRecord = { id: string; title: string; topic: string; body: string; status: string; sourceFactIds: string[]; sourceIdeaId: string | null; failureReason: string | null; reviewedAt: Date | null; approvedAt: Date | null; scheduledAt: Date | null; publishedAt: Date | null; createdAt: Date; updatedAt: Date; revisions: Array<{ id: string; version: number; body: string; changeType: string; createdAt: Date }>; critiques: Array<{ provider: string; result: unknown }> };
function serialise(item: DraftRecord) { return { ...item, reviewedAt: item.reviewedAt?.toISOString() ?? null, approvedAt: item.approvedAt?.toISOString() ?? null, scheduledAt: item.scheduledAt?.toISOString() ?? null, publishedAt: item.publishedAt?.toISOString() ?? null, createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString(), revisions: item.revisions.map(r => ({ ...r, createdAt: r.createdAt.toISOString() })), critiques: item.critiques.map(c => ({ provider: c.provider, ...(typeof c.result === 'object' && c.result !== null ? c.result : {}), factStatus: 'critique_only' })) }; }
export const getStrategy = (userId: string) => prisma.contentStrategy.findUnique({ where: { userId } });
export async function saveStrategy(userId: string, input: unknown) { const data = contentStrategySchema.parse(input); return prisma.contentStrategy.upsert({ where: { userId }, create: { userId, ...data }, update: data }); }
export const listPillars = (userId: string) => prisma.contentPillar.findMany({ where: { userId }, orderBy: { name: 'asc' } });
export async function createPillar(userId: string, input: unknown) { const data = z.object({ name: z.string().trim().min(1).max(120), description: z.string().trim().max(500).default('') }).parse(input); return prisma.contentPillar.create({ data: { userId, ...data } }); }
export async function deletePillar(userId: string, id: string) { const result = await prisma.contentPillar.deleteMany({ where: { id, userId } }); if (!result.count) throw new ContentNotFoundError(); }
export const listIdeas = (userId: string) => prisma.contentIdea.findMany({ where: { userId }, include: { pillar: true }, orderBy: { createdAt: 'desc' } });
export async function createIdea(userId: string, input: unknown) { return prisma.contentIdea.create({ data: { userId, ...contentIdeaSchema.parse(input) } }); }
export async function generateDraft(userId: string, input: unknown) { const request = contentGenerationRequestSchema.parse(input); const strategy = await getStrategy(userId); const result = await createContentProvider().generate({ ...request, audience: strategy?.targetAudience ?? '', voice: strategy?.writingVoice ?? '', facts: await facts(userId) }); return prisma.$transaction(async tx => { const draft = await tx.contentDraft.create({ data: { userId, title: request.title, topic: request.topic, body: result.body, sourceIdeaId: request.sourceIdeaId, sourceFactIds: result.sourceFactIds } }); await tx.contentRevision.create({ data: { draftId: draft.id, version: 1, body: result.body, changeType: 'generated' } }); if (request.sourceIdeaId) await tx.contentIdea.updateMany({ where: { id: request.sourceIdeaId, userId }, data: { status: 'USED' } }); return tx.contentDraft.findUniqueOrThrow({ where: { id: draft.id }, include }); }); }
export const listDrafts = async (userId: string) => (await prisma.contentDraft.findMany({ where: { userId }, include, orderBy: { updatedAt: 'desc' } })).map(serialise);
export const getDraft = async (userId: string, id: string) => { const item = await prisma.contentDraft.findFirst({ where: { id, userId }, include }); if (!item) throw new ContentNotFoundError(); return serialise(item); };
export async function createDraft(userId: string, input: unknown) { const data = contentDraftCreateSchema.parse(input); const draft = await prisma.contentDraft.create({ data: { userId, ...data } }); await prisma.contentRevision.create({ data: { draftId: draft.id, version: 1, body: draft.body, changeType: 'created' } }); return getDraft(userId, draft.id); }
const allowed: Record<ContentStatus, ContentStatus[]> = { DRAFT: ['REVIEW'], REVIEW: ['DRAFT', 'APPROVED'], APPROVED: ['SCHEDULED'], SCHEDULED: ['PUBLISHING'], PUBLISHING: ['PUBLISHED', 'PUBLISH_FAILED'], PUBLISHED: [], PUBLISH_FAILED: ['DRAFT'] };
export function canTransition(from: ContentStatus, to: ContentStatus) { return from === to || (allowed[from] ?? []).includes(to); }
export async function updateDraft(userId: string, id: string, input: unknown) { const data = contentDraftUpdateSchema.parse(input); const current = await prisma.contentDraft.findFirst({ where: { id, userId } }); if (!current) throw new ContentNotFoundError(); if (data.status && data.status !== current.status && !(allowed[current.status as ContentStatus] ?? []).includes(data.status as ContentStatus)) throw new InvalidContentTransitionError(`Cannot move content from ${current.status} to ${data.status}`); const changed = data.body !== undefined && data.body !== current.body; const updateData: Prisma.ContentDraftUpdateInput = {}; if (data.title !== undefined) updateData.title = data.title; if (data.topic !== undefined) updateData.topic = data.topic; if (data.body !== undefined) updateData.body = data.body; if (data.sourceIdeaId !== undefined) updateData.sourceIdea = data.sourceIdeaId ? { connect: { id: data.sourceIdeaId } } : { disconnect: true }; if (data.status !== undefined) updateData.status = data.status; if (data.status === 'REVIEW') updateData.reviewedAt = new Date(); if (data.status === 'APPROVED') updateData.approvedAt = new Date(); await prisma.$transaction(async tx => { await tx.contentDraft.update({ where: { id }, data: updateData }); if (changed) { const last = await tx.contentRevision.findFirst({ where: { draftId: id }, orderBy: { version: 'desc' } }); await tx.contentRevision.create({ data: { draftId: id, version: (last?.version ?? 0) + 1, body: data.body!, changeType: 'edited' } }); } }); return getDraft(userId, id); }
export async function transformDraft(userId: string, id: string, input: unknown) { const data = contentTransformSchema.parse(input); const current = await prisma.contentDraft.findFirst({ where: { id, userId } }); if (!current) throw new ContentNotFoundError(); const strategy = await getStrategy(userId); const result = await createContentProvider().transform({ title: current.title, topic: current.topic, body: current.body, action: data.action, audience: strategy?.targetAudience ?? '', voice: strategy?.writingVoice ?? '', facts: await facts(userId) }); return updateDraft(userId, id, { body: result.body }); }
export async function critiqueDraft(userId: string, id: string) { const current = await prisma.contentDraft.findFirst({ where: { id, userId } }); if (!current) throw new ContentNotFoundError(); const result = await createContentProvider().critique({ body: current.body, facts: await facts(userId) }); await prisma.contentCritique.create({ data: { draftId: id, provider: result.provider, result } }); return result; }
export async function publishDraft(userId: string, id: string) { const current = await prisma.contentDraft.findFirst({ where: { id, userId } }); if (!current) throw new ContentNotFoundError(); if (current.status !== 'APPROVED') throw new InvalidContentTransitionError('Only approved content can be published.'); const result = await createPublishingProvider().publish({ title: current.title, body: current.body }); await prisma.contentDraft.update({ where: { id }, data: result.status === 'published' ? { status: 'PUBLISHED', publishedAt: new Date(), failureReason: null } : { status: 'PUBLISH_FAILED', failureReason: result.reason ?? 'Publishing failed.' } }); return { result, draft: await getDraft(userId, id) }; }
export function contentErrorStatus(error: unknown) { if (error instanceof ContentNotFoundError) return 404; if (error instanceof InvalidContentTransitionError) return 409; return 500; }
