import { prisma } from './prisma.js';
import { achievementSchema, certificationSchema, educationSchema, experienceSchema, profileDetailsSchema, projectSchema, skillSchema, type AchievementInput, type CertificationInput, type ProfileDetails } from '@pba/shared';

export class ProfileNotFoundError extends Error { constructor() { super('Profile item not found'); this.name = 'ProfileNotFoundError'; } }
export const profileInclude = { experiences: { orderBy: { startDate: 'desc' as const } }, educations: { orderBy: { startDate: 'desc' as const } }, skills: { orderBy: { name: 'asc' as const } }, projects: { orderBy: { name: 'asc' as const } }, certifications: { orderBy: { issuedAt: 'desc' as const } }, achievements: { orderBy: { title: 'asc' as const } } };
export const getProfile = (userId: string) => prisma.profile.findUnique({ where: { userId }, include: profileInclude });
export async function upsertProfile(userId: string, input: ProfileDetails, email?: string) { const existingUser = await prisma.user.findUnique({ where: { id: userId }, select: { id: true } }); if (!existingUser) { if (!email) { const error = new Error('x-user-email header is required for a new user'); error.name = 'MissingUserEmailError'; throw error; } await prisma.user.create({ data: { id: userId, email } }); } const details = profileDetailsSchema.parse(input); const { professionalTitle, ...rest } = details; return prisma.profile.upsert({ where: { userId }, create: { userId, ...rest, headline: professionalTitle }, update: { ...rest, headline: professionalTitle }, include: profileInclude }); }
async function profileId(userId: string) { const profile = await prisma.profile.findUnique({ where: { userId }, select: { id: true } }); if (!profile) throw new ProfileNotFoundError(); return profile.id; }
function dates<T extends { startDate: string; endDate: string | null }>(input: T): Omit<T, 'startDate' | 'endDate'> & { startDate: Date; endDate: Date | null } { return { ...input, startDate: new Date(input.startDate), endDate: input.endDate ? new Date(input.endDate) : null }; }
export async function createExperience(u: string, i: unknown) { return prisma.experience.create({ data: { ...dates(experienceSchema.parse(i)), profileId: await profileId(u) } }); }
export async function updateExperience(u: string, id: string, i: unknown) { const result = await prisma.experience.updateMany({ where: { id, profile: { userId: u } }, data: dates(experienceSchema.parse(i)) }); if (!result.count) throw new ProfileNotFoundError(); return prisma.experience.findUniqueOrThrow({ where: { id } }); }
export async function deleteExperience(u: string, id: string) { const result = await prisma.experience.deleteMany({ where: { id, profile: { userId: u } } }); if (!result.count) throw new ProfileNotFoundError(); }
export async function createEducation(u: string, i: unknown) { return prisma.education.create({ data: { ...dates(educationSchema.parse(i)), profileId: await profileId(u) } }); }
export async function updateEducation(u: string, id: string, i: unknown) { const result = await prisma.education.updateMany({ where: { id, profile: { userId: u } }, data: dates(educationSchema.parse(i)) }); if (!result.count) throw new ProfileNotFoundError(); return prisma.education.findUniqueOrThrow({ where: { id } }); }
export async function deleteEducation(u: string, id: string) { const result = await prisma.education.deleteMany({ where: { id, profile: { userId: u } } }); if (!result.count) throw new ProfileNotFoundError(); }
export async function createProject(u: string, i: unknown) { return prisma.project.create({ data: { ...projectSchema.parse(i), profileId: await profileId(u) } }); }
export async function updateProject(u: string, id: string, i: unknown) { const result = await prisma.project.updateMany({ where: { id, profile: { userId: u } }, data: projectSchema.parse(i) }); if (!result.count) throw new ProfileNotFoundError(); return prisma.project.findUniqueOrThrow({ where: { id } }); }
export async function deleteProject(u: string, id: string) { const result = await prisma.project.deleteMany({ where: { id, profile: { userId: u } } }); if (!result.count) throw new ProfileNotFoundError(); }
export async function createSkill(u: string, i: unknown) { return prisma.skill.create({ data: { ...skillSchema.parse(i), profileId: await profileId(u) } }); }
export async function updateSkill(u: string, id: string, i: unknown) { const result = await prisma.skill.updateMany({ where: { id, profile: { userId: u } }, data: skillSchema.parse(i) }); if (!result.count) throw new ProfileNotFoundError(); return prisma.skill.findUniqueOrThrow({ where: { id } }); }
export async function deleteSkill(u: string, id: string) { const result = await prisma.skill.deleteMany({ where: { id, profile: { userId: u } } }); if (!result.count) throw new ProfileNotFoundError(); }
export async function createCertification(u: string, i: CertificationInput) { const value = certificationSchema.parse(i); return prisma.certification.create({ data: { ...value, issuedAt: value.issuedAt ? new Date(value.issuedAt) : null, profileId: await profileId(u) } }); }
export async function createAchievement(u: string, i: AchievementInput) { return prisma.achievement.create({ data: { ...achievementSchema.parse(i), profileId: await profileId(u) } }); }
