import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { CheckCircle2, FileText, Sparkles } from 'lucide-react';
import { EmptyState } from '../components/EmptyState';
import { FormField, SelectField, TextAreaField } from '../components/FormField';
import { listJobs } from '../lib/jobApi';
import { listResumes } from '../lib/resumeApi';
import { generateApplicationPackage, updateCoverLetter } from '../lib/applicationPackageApi';
import type { ApplicationPackage } from '@pba/shared';

export function ApplicationPackagePage() {
  if (!import.meta.env.VITE_USER_ID) return <EmptyState title="Connect your workspace first" description="Set VITE_USER_ID to the ID of your authenticated user, then reload." />;
  const resumes = useQuery({ queryKey: ['resumes', 'package'], queryFn: listResumes, retry: false });
  const jobs = useQuery({ queryKey: ['jobs', 'package'], queryFn: () => listJobs({}), retry: false });
  const [packageValue, setPackageValue] = useState<ApplicationPackage>();
  const [resumeId, setResumeId] = useState(''); const [jobId, setJobId] = useState(''); const [company, setCompany] = useState(''); const [role, setRole] = useState(''); const [description, setDescription] = useState('');
  const generate = useMutation({ mutationFn: () => generateApplicationPackage({ resumeId, jobId: jobId || null, company, role, jobDescription: description }), onSuccess: result => setPackageValue(result.package) });
  const save = useMutation({ mutationFn: (content: string) => updateCoverLetter(packageValue!.coverLetterId, content), onSuccess: result => setPackageValue(current => current ? { ...current, coverLetter: { ...current.coverLetter, content: result.coverLetter.content } } : current) });
  const selectJob = (id: string) => { setJobId(id); const job = jobs.data?.jobs.find(item => item.id === id); if (job) { setCompany(job.company); setRole(job.title); setDescription(job.description ?? ''); } };
  if (resumes.isPending || jobs.isPending) return <div aria-label="Loading application package" className="card h-72 animate-pulse bg-slate-100" />;
  if (resumes.isError || jobs.isError) return <EmptyState title="Application package data could not be loaded" description={(resumes.error ?? jobs.error)?.message ?? 'Try again.'} />;
  return <div><header className="mb-8"><h1 className="text-2xl font-bold tracking-tight lg:text-3xl">Application package</h1><p className="muted mt-2 max-w-2xl">Prepare a truthful, reviewable package from one of your saved resumes and a real job description.</p></header><section className="card p-5"><div className="grid gap-4 md:grid-cols-2"><SelectField label="Resume" value={resumeId} onChange={e => setResumeId(e.target.value)}><option value="">Select a resume</option>{resumes.data.resumes.map(resume => <option key={resume.id} value={resume.id}>{resume.title}{resume.latestVersion ? ` · v${resume.latestVersion.version}` : ''}</option>)}</SelectField><SelectField label="Existing job (optional)" value={jobId} onChange={e => selectJob(e.target.value)}><option value="">Enter job details below</option>{jobs.data.jobs.map(job => <option key={job.id} value={job.id}>{job.title} · {job.company}</option>)}</SelectField><FormField label="Company" value={company} onChange={e => setCompany(e.target.value)} placeholder="Company name" /><FormField label="Role" value={role} onChange={e => setRole(e.target.value)} placeholder="Target role" /></div><div className="mt-4"><TextAreaField label="Job description" value={description} onChange={e => setDescription(e.target.value)} rows={8} placeholder="Paste the complete job description. The assistant will not add qualifications that are not in your profile." /></div>{generate.isError && <p role="alert" className="mt-3 text-sm text-rose-600">{generate.error.message}</p>}<button type="button" onClick={() => generate.mutate()} disabled={generate.isPending || !resumeId || !company || !role || description.trim().length < 40} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Sparkles size={17} />{generate.isPending ? 'Preparing…' : 'Generate package'}</button></section>{packageValue && <PackageReview key={packageValue.coverLetterId} value={packageValue} save={content => save.mutate(content)} saving={save.isPending} saveError={save.error?.message ?? ''} />}</div>;
}

function PackageReview({ value, save, saving, saveError }: { value: ApplicationPackage; save: (content: string) => void; saving: boolean; saveError?: string }) {
  const [content, setContent] = useState(value.coverLetter.content);
  return <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(280px,0.8fr)]"><section className="card p-5"><div className="flex items-center gap-2"><FileText size={18} className="text-indigo-600" /><h2 className="font-semibold">Review and edit cover letter</h2></div><p className="muted mt-1">Generated text is derived from your supplied facts. Edit it before you use it.</p><TextAreaField label="Cover letter" value={content} onChange={e => setContent(e.target.value)} rows={18} /><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-slate-500">Provider: {value.coverLetter.provider} · Original resume preserved</span><button type="button" onClick={() => save(content)} disabled={saving || content.trim().length < 80} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save edited letter'}</button></div>{saveError && <p role="alert" className="mt-3 text-sm text-rose-600">{saveError}</p>}</section><aside className="space-y-5"><ReviewList title="Skills match" items={value.skillsMatch} empty="No matching terms found in the supplied facts." /><ReviewList title="Skills gap to review" items={value.skillsGap} empty="No obvious gaps identified." /><section className="card p-5"><h2 className="font-semibold">Interview preparation</h2><div className="mt-3 space-y-4">{value.interviewPreparation.length ? value.interviewPreparation.map(item => <div key={item.question}><p className="text-sm font-medium">{item.question}</p><p className="mt-1 text-xs text-slate-600">{item.preparation}</p></div>) : <p className="text-sm text-slate-500">No prompts generated.</p>}</div></section><section className="card p-5"><h2 className="font-semibold">Application checklist</h2><ul className="mt-3 space-y-2">{value.checklist.map(item => <li key={item} className="flex gap-2 text-sm text-slate-600"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-600" />{item}</li>)}</ul></section></aside></div>;
}
function ReviewList({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <section className="card p-5"><h2 className="font-semibold">{title}</h2>{items.length ? <ul className="mt-3 flex flex-wrap gap-2">{items.map(item => <li key={item} className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-medium text-indigo-700">{item}</li>)}</ul> : <p className="mt-2 text-sm text-slate-500">{empty}</p>}</section>; }
