import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { PublicNav } from './PublicPages';
import { forgotPassword, signin, signup } from '../lib/authApi';
import { getSessionUser } from '../lib/session';
import { FormField } from '../components/FormField';

function AuthFrame({ title, children }: { title: string; children: ReactNode }) { return <div className="min-h-screen bg-slate-50"><PublicNav/><main className="mx-auto max-w-md px-5 py-14"><div className="card p-6 lg:p-8"><h1 className="text-2xl font-bold">{title}</h1>{children}</div></main></div>; }
function finish(user: { onboardingCompleted: boolean }, navigate: ReturnType<typeof useNavigate>) { navigate(user.onboardingCompleted ? '/dashboard' : '/onboarding', { replace: true }); }
export function SignUpPage() { const navigate = useNavigate(); const location = useLocation(); const plan = new URLSearchParams(location.search).get('plan') ?? 'FREE'; const [form, setForm] = useState({ email: '', password: '', confirm: '', acceptTerms: false }); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (form.password !== form.confirm) return setError('Passwords must match.'); setPending(true); try { const result = await signup({ email: form.email, password: form.password, acceptTerms: true, plan }); finish(result.user, navigate); } catch (e) { setError(e instanceof Error ? e.message : 'Sign up failed.'); } finally { setPending(false); } }; return <AuthFrame title="Create your workspace"><p className="muted mt-2">Start with a free workspace. You can review plans before any paid activation.</p><form onSubmit={submit} className="mt-6 space-y-4"><FormField label="Email" type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><FormField label="Password" type="password" minLength={12} required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/><FormField label="Confirm password" type="password" minLength={12} required value={form.confirm} onChange={e => setForm({ ...form, confirm: e.target.value })}/><label className="flex gap-2 text-sm text-slate-600"><input type="checkbox" required checked={form.acceptTerms} onChange={e => setForm({ ...form, acceptTerms: e.target.checked })}/>I agree to the <Link className="text-indigo-700" to="/terms">terms</Link>.</label>{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}<button disabled={pending} className="w-full rounded-lg bg-indigo-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Creating…' : 'Create account'}</button></form><p className="mt-6 text-center text-sm text-slate-600">Already have an account? <Link className="font-semibold text-indigo-700" to="/signin">Sign in</Link></p></AuthFrame>; }
export function SignInPage() { const navigate = useNavigate(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(''); try { const result = await signin(form); finish(result.user, navigate); } catch (e) { setError(e instanceof Error ? e.message : 'Sign in failed.'); } finally { setPending(false); } }; return <AuthFrame title="Welcome back"><form onSubmit={submit} className="mt-6 space-y-4"><FormField label="Email" type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><FormField label="Password" type="password" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/><div className="text-right"><Link className="text-sm font-semibold text-indigo-700" to="/forgot-password">Forgot password?</Link></div>{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}<button disabled={pending} className="w-full rounded-lg bg-indigo-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Signing in…' : 'Sign in'}</button></form><p className="mt-6 text-center text-sm text-slate-600">New here? <Link className="font-semibold text-indigo-700" to="/signup">Create an account</Link></p></AuthFrame>; }
export function ForgotPasswordPage() { const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [pending, setPending] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); await forgotPassword(email).catch(() => undefined); setPending(false); setSent(true); }; return <AuthFrame title="Reset your password">{sent ? <p className="mt-4 text-sm text-slate-600">If an account matches that email, reset instructions will be sent.</p> : <form onSubmit={submit} className="mt-6 space-y-4"><FormField label="Email" type="email" required value={email} onChange={e => setEmail(e.target.value)}/><button disabled={pending} className="w-full rounded-lg bg-indigo-600 px-4 py-3 text-sm font-semibold text-white">{pending ? 'Sending…' : 'Send reset instructions'}</button></form>}</AuthFrame>; }
function hasIdentity() { return Boolean(getSessionUser() || import.meta.env.VITE_USER_ID); }
export function AuthRedirect({ children }: { children: ReactNode }) { return hasIdentity() ? <Navigate to="/dashboard" replace/> : <>{children}</>; }
export function RequireSession({ children }: { children: ReactNode }) { return hasIdentity() ? <>{children}</> : <Navigate to="/signin" replace/>; }
