/* eslint-disable @typescript-eslint/ban-ts-comment */
// MUI v7's polymorphic component typings are overly strict for the compact composition used here.
// @ts-nocheck
import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { Alert, Box, Button, Card, Checkbox, Container, FormControlLabel, Stack, Typography } from '@mui/material';
import { PublicNav } from './PublicPages';
import { forgotPassword, signin, signup } from '../lib/authApi';
import { getSessionUser } from '../lib/session';
import { FormField } from '../components/FormField';
function AuthFrame({ title, children }: { title: string; children: ReactNode }) { return <Box sx={{ minHeight: '100vh', bgcolor: 'background.default' }}><PublicNav /><Container maxWidth="sm" sx={{ py: { xs: 6, md: 10 } }}><Card sx={{ p: { xs: 3, md: 5 } }}><Typography variant="h1" sx={{ fontSize: '2rem' }}>{title}</Typography>{children}</Card></Container></Box>; }
function finish(user: { onboardingCompleted: boolean }, navigate: ReturnType<typeof useNavigate>) { navigate(user.onboardingCompleted ? '/dashboard' : '/onboarding', { replace: true }); }
export function SignUpPage() { const navigate = useNavigate(); const location = useLocation(); const plan = new URLSearchParams(location.search).get('plan') ?? 'FREE'; const [form, setForm] = useState({ email: '', password: '', confirm: '', acceptTerms: false }); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (form.password !== form.confirm) return setError('Passwords must match.'); setPending(true); try { const result = await signup({ email: form.email, password: form.password, acceptTerms: true, plan }); finish(result.user, navigate); } catch (e) { setError(e instanceof Error ? e.message : 'Sign up failed.'); } finally { setPending(false); } }; return <AuthFrame title="Create your workspace"><Typography color="text.secondary" sx={{ mt: 1 }}>Start with a free workspace. You can review plans before any paid activation.</Typography><Stack component="form" onSubmit={submit} spacing={2} sx={{ mt: 4 }}><FormField label="Email" type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><FormField label="Password" type="password" minLength={12} required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><FormField label="Confirm password" type="password" minLength={12} required value={form.confirm} onChange={e => setForm({ ...form, confirm: e.target.value })} /><FormControlLabel control={<Checkbox required checked={form.acceptTerms} onChange={e => setForm({ ...form, acceptTerms: e.target.checked })} />} label={<Typography variant="body2">I agree to the <Link to="/terms">terms</Link>.</Typography>} />{error && <Alert severity="error">{error}</Alert>}<Button type="submit" variant="contained" size="large" disabled={pending}>{pending ? 'Creating…' : 'Create account'}</Button></Stack><Typography variant="body2" textAlign="center" color="text.secondary" sx={{ mt: 3 }}>Already have an account? <Link to="/signin">Sign in</Link></Typography></AuthFrame>; }
export function SignInPage() { const navigate = useNavigate(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(''); try { const result = await signin(form); finish(result.user, navigate); } catch (e) { setError(e instanceof Error ? e.message : 'Sign in failed.'); } finally { setPending(false); } }; return <AuthFrame title="Welcome back"><Stack component="form" onSubmit={submit} spacing={2} sx={{ mt: 4 }}><FormField label="Email" type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><FormField label="Password" type="password" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><Box textAlign="right"><Link to="/forgot-password">Forgot password?</Link></Box>{error && <Alert severity="error">{error}</Alert>}<Button type="submit" variant="contained" size="large" disabled={pending}>{pending ? 'Signing in…' : 'Sign in'}</Button></Stack><Typography variant="body2" textAlign="center" color="text.secondary" sx={{ mt: 3 }}>New here? <Link to="/signup">Create an account</Link></Typography></AuthFrame>; }
export function ForgotPasswordPage() { const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [pending, setPending] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); await forgotPassword(email).catch(() => undefined); setPending(false); setSent(true); }; return <AuthFrame title="Reset your password">{sent ? <Alert severity="success" sx={{ mt: 3 }}>If an account matches that email, reset instructions will be sent.</Alert> : <Stack component="form" onSubmit={submit} spacing={2} sx={{ mt: 4 }}><FormField label="Email" type="email" required value={email} onChange={e => setEmail(e.target.value)} /><Button type="submit" variant="contained" size="large" disabled={pending}>{pending ? 'Sending…' : 'Send reset instructions'}</Button></Stack>}</AuthFrame>; }
function hasIdentity() { return Boolean(getSessionUser() || import.meta.env.VITE_USER_ID); }
export function AuthRedirect({ children }: { children: ReactNode }) { return hasIdentity() ? <Navigate to="/dashboard" replace /> : <>{children}</>; }
export function RequireSession({ children }: { children: ReactNode }) { return hasIdentity() ? <>{children}</> : <Navigate to="/signin" replace />; }
