import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, MessageCircleQuestion, Save } from 'lucide-react';
import { interviewStageSchema, type InterviewPreparationResponse, type InterviewStage } from '@pba/shared';
import { EmptyState } from '../components/EmptyState';
import { FormField, SelectField, TextAreaField } from '../components/FormField';
import { listApplications, type ApplicationRecord } from '../lib/applicationApi';
import { generateInterviewPreparation, getInterviewPreparation, updateInterviewPreparation } from '../lib/interviewPreparationApi';

const stages = interviewStageSchema.options;
export function InterviewPreparationPage() {
  if (!import.meta.env.VITE_USER_ID) return <EmptyState title="Connect your workspace first" description="Set VITE_USER_ID to the ID of your authenticated user, then reload." />;
  const applications = useQuery({ queryKey: ['applications', 'interview-preparation'], queryFn: () => listApplications({}), retry: false });
  const [selected, setSelected] = useState('');
  useEffect(() => { if (!selected && applications.data?.applications[0]) setSelected(applications.data.applications[0].id); }, [applications.data, selected]);
  if (applications.isPending) return <div aria-label="Loading applications" className="card h-72 animate-pulse bg-slate-100" />;
  if (applications.isError) return <EmptyState title="Applications could not be loaded" description={applications.error.message} />;
  if (applications.data.applications.length === 0) return <EmptyState title="Track an application first" description="Interview preparation is connected to an application so the selected job and its description remain the source of truth." />;
  const application = applications.data.applications.find(item => item.id === selected) ?? applications.data.applications[0];
  if (!application) return <EmptyState title="Select an application" description="Choose an application to prepare for its interview." />;
  return <div><div className="mb-5 max-w-xl"><SelectField label="Select an application / job" value={application.id} onChange={event => setSelected(event.target.value)}>{applications.data.applications.map(item => <option key={item.id} value={item.id}>{item.job.title} · {item.job.company}</option>)}</SelectField></div><InterviewWorkspace key={application.id} application={application} /></div>;
}

function InterviewWorkspace({ application }: { application: ApplicationRecord }) {
  const client = useQueryClient(); const preparation = useQuery({ queryKey: ['interview-preparation', application.id], queryFn: () => getInterviewPreparation(application.id), retry: false });
  const [stage, setStage] = useState<InterviewStage>('Technical Interview'); const [scheduledAt, setScheduledAt] = useState(''); const [notes, setNotes] = useState(''); const [answers, setAnswers] = useState<Record<string, string>>({});
  useEffect(() => { const value = preparation.data?.interview; if (value) { setStage(value.stage); setScheduledAt(value.scheduledAt ? value.scheduledAt.slice(0, 16) : ''); setNotes(value.notes); setAnswers(Object.fromEntries(value.answers.map(answer => [answer.questionId, answer.answer]))); } }, [preparation.data]);
  const generate = useMutation({ mutationFn: () => generateInterviewPreparation(application.id, { stage, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : null, notes }), onSuccess: () => void client.invalidateQueries({ queryKey: ['interview-preparation', application.id] }) });
  const save = useMutation({ mutationFn: () => updateInterviewPreparation(application.id, { stage, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : null, notes, answers: Object.entries(answers).map(([questionId, answer]) => ({ questionId, answer })) }), onSuccess: result => { void client.invalidateQueries({ queryKey: ['interview-preparation', application.id] }); setAnswers(Object.fromEntries(result.interview.answers.map(answer => [answer.questionId, answer.answer]))); } });
  if (preparation.isPending) return <div aria-label="Loading interview preparation" className="card h-72 animate-pulse bg-slate-100" />;
  if (preparation.isError) return <EmptyState title="Interview preparation could not be loaded" description={preparation.error.message} />;
  const value = preparation.data.interview;
  return <div><header className="mb-8"><div className="flex items-center gap-2 text-indigo-600"><MessageCircleQuestion size={20} /><span className="text-sm font-semibold">Preparation workspace</span></div><h1 className="mt-2 text-2xl font-bold tracking-tight lg:text-3xl">{application.job.title} interview prep</h1><p className="muted mt-2">{application.job.company} · Generated material is a practice aid, not a prediction of the interview.</p></header><section className="card p-5"><div className="grid gap-4 md:grid-cols-2"><SelectField label="Interview stage" value={stage} onChange={e => setStage(e.target.value as InterviewStage)}>{stages.map(item => <option key={item}>{item}</option>)}</SelectField><FormField label="Interview date" type="datetime-local" value={scheduledAt} onChange={e => setScheduledAt(e.target.value)} /></div><div className="mt-4"><TextAreaField label="Your preparation notes" value={notes} onChange={e => setNotes(e.target.value)} rows={4} placeholder="Add logistics, topics to revisit, or questions for the interviewer." /></div><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={() => generate.mutate()} disabled={generate.isPending} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{generate.isPending ? 'Generating…' : value ? 'Regenerate preparation' : 'Generate preparation'}</button>{value && <button type="button" onClick={() => save.mutate()} disabled={save.isPending} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 disabled:opacity-50"><Save size={16} />{save.isPending ? 'Saving…' : 'Save notes and answers'}</button>}{(generate.isError || save.isError) && <p role="alert" className="text-sm text-rose-600">{(generate.error ?? save.error)?.message}</p>}</div></section>{value ? <PreparationContent value={value} answers={answers} setAnswer={(id, answer) => setAnswers(current => ({ ...current, [id]: answer }))} /> : <div className="card mt-5 p-8 text-center"><CalendarDays className="mx-auto text-indigo-500" size={28} /><p className="mt-3 font-semibold">No preparation generated yet</p><p className="muted mt-1">Choose the interview stage and generate role-aware practice material.</p></div>}</div>;
}

function PreparationContent({ value, answers, setAnswer }: { value: InterviewPreparationResponse; answers: Record<string, string>; setAnswer: (id: string, answer: string) => void }) {
  const groups = [{ title: 'Resume-based questions', questions: value.preparation.resumeQuestions }, { title: 'Behavioral questions', questions: value.preparation.behavioralQuestions }, { title: 'Role-specific questions', questions: value.preparation.roleSpecificQuestions }];
  return <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(280px,0.75fr)]"><main className="space-y-5"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{value.preparation.disclaimer}</div>{groups.map(group => <section key={group.title} className="card p-5"><h2 className="font-semibold">{group.title}</h2><div className="mt-4 space-y-5">{group.questions.map(item => <div key={item.id}><p className="text-sm font-medium">{item.question}</p><p className="mt-1 text-xs text-slate-500">Write your own answer below. Linked facts: {item.sourceFactIds.length ? item.sourceFactIds.join(', ') : 'none'}</p><textarea aria-label={`Your answer for ${item.question}`} value={answers[item.id] ?? ''} onChange={e => setAnswer(item.id, e.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-indigo-500" placeholder="Record your answer or talking points…" /></div>)}</div></section>)}</main><aside className="space-y-5"><section className="card p-5"><h2 className="font-semibold">Technical topics</h2><div className="mt-3 flex flex-wrap gap-2">{value.preparation.technicalTopics.map(topic => <span key={topic} className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-medium text-indigo-700">{topic}</span>)}</div><h3 className="mt-5 text-sm font-semibold">Likely topic categories</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{value.preparation.likelyTopicCategories.map(category => <li key={category}>{category}</li>)}</ul></section><section className="card p-5"><h2 className="font-semibold">Preparation checklist</h2><ul className="mt-3 space-y-2">{value.preparation.checklist.map(item => <li key={item} className="text-sm text-slate-600">□ {item}</li>)}</ul></section></aside></div>;
}
