import { useState } from 'react';
import type { FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { FormField, TextAreaField } from '../components/FormField';
import { saveProfile } from '../lib/profileApi';
import { getSessionUser } from '../lib/session';
import { saveStrategy } from '../lib/contentApi';
import { completeOnboarding } from '../lib/authApi';
export function OnboardingPage() { const navigate = useNavigate(); const [form, setForm] = useState({ firstName: '', lastName: '', professionalTitle: '', yearsOfExperience: '0', skills: '', audience: '', voice: '', frequency: 'Weekly' }); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); try { await saveProfile({ firstName: form.firstName, lastName: form.lastName, professionalTitle: form.professionalTitle, location: '', phone: '', website: '', summary: '', yearsOfExperience: Number(form.yearsOfExperience), targetRoles: [], preferredLocations: [], remotePreference: 'flexible' }); await saveStrategy({ targetAudience: form.audience, writingVoice: form.voice, postingFrequency: form.frequency, recurringThemes: form.skills.split(',').map(value => value.trim()).filter(Boolean) }); await completeOnboarding(); navigate('/dashboard', { replace: true }); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save onboarding.'); } finally { setPending(false); } }; if (!getSessionUser()) return null; return <main className="min-h-screen bg-slate-50 px-5 py-10"><div className="mx-auto max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-600">Personal Brand Assistant</p><h1 className="mt-4 text-3xl font-bold">Build your starting point</h1><p className="muted mt-2">A few accurate details are enough to begin. You can skip deeper profile work and complete it later.</p><form onSubmit={submit} className="card mt-8 space-y-5 p-6"><div className="grid gap-4 md:grid-cols-2"><FormField label="First name" required value={form.firstName} onChange={e => setForm({ ...form, firstName: e.target.value })}/><FormField label="Last name" value={form.lastName} onChange={e => setForm({ ...form, lastName: e.target.value })}/></div><FormField label="Professional title" required placeholder="e.g. Senior software engineer" value={form.professionalTitle} onChange={e => setForm({ ...form, professionalTitle: e.target.value })}/><FormField label="Years of experience" type="number" min="0" max="80" value={form.yearsOfExperience} onChange={e => setForm({ ...form, yearsOfExperience: e.target.value })}/><TextAreaField label="Skills or content interests (comma separated)" value={form.skills} onChange={e => setForm({ ...form, skills: e.target.value })}/><TextAreaField label="Who do you want to reach?" value={form.audience} onChange={e => setForm({ ...form, audience: e.target.value })}/><TextAreaField label="How should your writing sound?" value={form.voice} onChange={e => setForm({ ...form, voice: e.target.value })}/>{error && <p role="alert" className="text-sm text-rose-600">{error}</p>}<button disabled={pending} className="rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Saving…' : 'Continue to dashboard'}</button></form></div></main>; }
