import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronDown, ChevronUp, Copy, FilePlus2, Save, Trash2 } from 'lucide-react';
import { type ResumeDocument, type ResumeSectionId } from '@pba/shared';
import { EmptyState } from '../components/EmptyState';
import { FormField, TextAreaField } from '../components/FormField';
import { OptimizationPanel } from '../components/OptimizationPanel';
import { createResume, deleteResume, duplicateResume, getResume, listResumes, autosaveResume, saveResumeVersion, type ResumeListItem } from '../lib/resumeApi';
import type { ProfileRecord } from '../lib/profileApi';

const sectionLabels: Record<ResumeSectionId, string> = { summary: 'Professional summary', experience: 'Experience', education: 'Education', skills: 'Skills', projects: 'Projects', certifications: 'Certifications', achievements: 'Achievements' };
function sectionTitle(value: ResumeSectionId) { return sectionLabels[value]; }

export function ResumePage() {
  const [selected, setSelected] = useState<string>(); const [creating, setCreating] = useState(false); const list = useQuery({ queryKey: ['resumes'], queryFn: listResumes, retry: false });
  useEffect(() => { if (!selected && list.data?.resumes[0]) setSelected(list.data.resumes[0].id); }, [list.data, selected]);
  if (!import.meta.env.VITE_USER_ID) return <EmptyState title="Connect your workspace first" description="Set VITE_USER_ID to the ID of your authenticated user, then reload. Resumes are never created for an invented user."/>;
  if (list.isPending) return <div aria-label="Loading resumes" className="space-y-4"><div className="h-10 w-72 animate-pulse rounded bg-slate-200"/><div className="card h-64 animate-pulse bg-slate-100"/></div>;
  if (list.isError) return <EmptyState title="Resumes could not be loaded" description={list.error.message}/>;
  if (selected) return <ResumeEditor id={selected} onBack={() => setSelected(undefined)} onChanged={() => void list.refetch()}/>;
  return <ResumeList resumes={list.data.resumes} creating={creating} setCreating={setCreating} onSelect={setSelected} onCreated={resume => { setCreating(false); setSelected(resume.id); void list.refetch(); }}/>
}

function ResumeList({ resumes, creating, setCreating, onSelect, onCreated }: { resumes: ResumeListItem[]; creating: boolean; setCreating: (value: boolean) => void; onSelect: (id: string) => void; onCreated: (resume: { id: string }) => void }) {
  const [title, setTitle] = useState(''); const mutation = useMutation({ mutationFn: () => createResume(title), onSuccess: result => onCreated(result.resume) });
  return <div><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight lg:text-3xl">Resume builder</h1><p className="muted mt-2">Create targeted, ATS-friendly resumes from your professional profile.</p></div><button type="button" onClick={() => setCreating(true)} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><FilePlus2 size={17}/>New resume</button></div>{creating&&<form onSubmit={e=>{e.preventDefault();if(title.trim()) mutation.mutate();}} className="card mb-5 flex flex-wrap items-end gap-3 p-5"><div className="min-w-64 flex-1"><FormField label="Resume name" autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Platform engineering resume"/></div><button type="submit" disabled={mutation.isPending} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{mutation.isPending?'Creating…':'Create'}</button><button type="button" onClick={()=>setCreating(false)} className="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-600">Cancel</button>{mutation.isError&&<p className="w-full text-sm text-rose-600">{mutation.error.message}</p>}</form>}{resumes.length===0?<EmptyState title="No resumes yet" description="Create your first resume to tailor your profile for a specific direction." action="New resume"/>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{resumes.map(resume=><button type="button" key={resume.id} onClick={()=>onSelect(resume.id)} className="card p-5 text-left transition hover:-translate-y-0.5 hover:border-indigo-300"><p className="font-semibold">{resume.title}</p><p className="muted mt-2">Version {resume.latestVersion?.version ?? 0}</p><p className="mt-6 text-xs text-slate-500">Updated {new Date(resume.updatedAt).toLocaleDateString()}</p></button>)}</div>}</div>;
}

function ResumeEditor({ id, onBack, onChanged }: { id: string; onBack: () => void; onChanged: () => void }) {
  const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['resume', id], queryFn: () => getResume(id), retry: false }); const [title, setTitle] = useState(''); const [document, setDocument] = useState<ResumeDocument>(); const hydrated = useRef(false); const [saveState, setSaveState] = useState('');
  useEffect(() => { const resume=query.data?.resume; if (resume?.latestVersion) { setTitle(resume.title); setDocument(resume.latestVersion.content); hydrated.current=true; } }, [query.data]);
  const draft = useMutation({ mutationFn: () => autosaveResume(id, title, document!), onSuccess: () => { setSaveState('Autosaved'); void queryClient.invalidateQueries({queryKey:['resume',id]}); }, onError: e => setSaveState(e.message) });
  const version = useMutation({ mutationFn: () => saveResumeVersion(id, title, document!), onSuccess: () => { setSaveState('Version saved'); void queryClient.invalidateQueries({queryKey:['resume',id]}); onChanged(); }, onError: e => setSaveState(e.message) });
  const duplicate = useMutation({ mutationFn: () => duplicateResume(id), onSuccess: () => onBack() }); const remove = useMutation({ mutationFn: () => deleteResume(id), onSuccess: () => { onChanged(); onBack(); } });
  useEffect(() => { if (!hydrated.current || !document) return; setSaveState('Saving…'); const timer=window.setTimeout(()=>draft.mutate(),800); return () => window.clearTimeout(timer); }, [document, title]);
  if (query.isPending) return <div aria-label="Loading resume" className="card h-96 animate-pulse bg-slate-100"/>;
  if (query.isError || !document) return <EmptyState title="Resume could not be loaded" description={query.error?.message ?? 'This resume has no saved document.'}/>;
  const profile=query.data.resume.profile; const update=(next: Partial<ResumeDocument>)=>setDocument({...document,...next});
  return <div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={onBack} className="text-sm font-semibold text-indigo-700">← All resumes</button><div className="flex items-center gap-2"><span className="text-xs text-slate-500">{saveState}</span><button type="button" onClick={()=>version.mutate()} disabled={version.isPending} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white"><Save size={16}/>Save version</button><button type="button" onClick={()=>duplicate.mutate()} className="rounded-lg border border-slate-200 p-2 text-slate-600" aria-label="Duplicate resume"><Copy size={17}/></button><button type="button" onClick={()=>{if(window.confirm('Delete this resume?'))remove.mutate();}} className="rounded-lg border border-slate-200 p-2 text-rose-600" aria-label="Delete resume"><Trash2 size={17}/></button></div></div><div className="mb-5"><OptimizationPanel resumeId={id} onApplied={content=>{setDocument(content);setSaveState('Optimized version created');void queryClient.invalidateQueries({queryKey:['resume',id]});}}/></div><div className="grid gap-5 xl:grid-cols-[minmax(360px,0.9fr)_minmax(480px,1.1fr)]"><div className="space-y-5"><section className="card p-5"><FormField label="Resume name" value={title} onChange={e=>setTitle(e.target.value)}/><div className="mt-4"><TextAreaField label="Professional summary" value={document.summary} onChange={e=>update({summary:e.target.value})}/></div></section><SectionSettings document={document} update={update}/></div><ResumePreview profile={profile} document={document} title={title}/></div></div>;
}

function SectionSettings({ document, update }: { document: ResumeDocument; update: (next: Partial<ResumeDocument>) => void }) { const move=(index:number,direction:number)=>{const next=[...document.sectionOrder];const target=index+direction;if(target<0||target>=next.length)return;const current=next[index];const targetValue=next[target];if(!current||!targetValue)return;next[index]=targetValue;next[target]=current;update({sectionOrder:next});};return <section className="card p-5"><h2 className="font-semibold">Resume sections</h2><p className="muted mt-1">Choose sections and adjust their order.</p><div className="mt-4 space-y-2">{document.sectionOrder.map((section,index)=><div key={section} className="flex items-center gap-2 rounded-lg border border-slate-100 p-2"><input type="checkbox" checked={document.visibleSections[section]} onChange={e=>update({visibleSections:{...document.visibleSections,[section]:e.target.checked}})} aria-label={`Show ${sectionTitle(section)}`}/><span className="flex-1 text-sm">{sectionTitle(section)}</span><button type="button" onClick={()=>move(index,-1)} aria-label="Move section up" className="rounded p-1 text-slate-500 hover:bg-slate-100"><ChevronUp size={16}/></button><button type="button" onClick={()=>move(index,1)} aria-label="Move section down" className="rounded p-1 text-slate-500 hover:bg-slate-100"><ChevronDown size={16}/></button></div>)}</div></section>; }

function ResumePreview({ profile, document, title }: { profile: ProfileRecord | null; document: ResumeDocument; title: string }) { if (!profile) return <div className="card p-8"><p className="text-sm text-slate-500">Complete your profile to preview a resume.</p></div>; const byId=(key: keyof ProfileRecord, ids:string[])=>((profile[key] as Array<{id:string}>)??[]).filter(item=>ids.includes(item.id));return <article className="card min-h-[760px] bg-white p-8 text-slate-900 shadow-md lg:p-10" aria-label="Live resume preview"><header className="border-b-2 border-slate-900 pb-5"><h1 className="text-3xl font-bold tracking-tight">{profile.firstName} {profile.lastName}</h1><p className="mt-1 text-base font-medium">{profile.headline}</p><p className="mt-2 text-xs text-slate-600">{[profile.location,profile.phone,profile.website].filter(Boolean).join(' · ')}</p></header>{document.sectionOrder.filter(section=>document.visibleSections[section]).map(section=><PreviewSection key={section} section={section} document={document} byId={byId}/>)}<p className="mt-8 text-right text-[10px] text-slate-400">{title} · Live preview</p></article>; }
function PreviewSection({ section, document, byId }: { section: ResumeSectionId; document: ResumeDocument; byId: (key:keyof ProfileRecord, ids:string[])=>Array<{id:string}> }) { if(section==='summary') return <section className="mt-5"><h2 className="resume-heading">SUMMARY</h2><p className="whitespace-pre-line text-xs leading-relaxed text-slate-700">{document.summary}</p></section>; const items=section==='experience'?byId('experiences',document.experienceIds):section==='education'?byId('educations',document.educationIds):section==='skills'?byId('skills',document.skillIds):section==='projects'?byId('projects',document.projectIds):section==='certifications'?byId('certifications',document.certificationIds):byId('achievements',document.achievementIds);return <section className="mt-5"><h2 className="resume-heading">{sectionTitle(section).toUpperCase()}</h2>{items.length===0?<p className="text-xs text-slate-500">No profile entries selected.</p>:<div className="space-y-3">{items.map((raw,index)=>{const item=raw as Record<string,unknown>;const description=typeof item.description==='string'?item.description:'';return <div key={String(item.id??index)} className="text-xs"><p className="font-semibold">{String(item.title??item.name??item.company??item.institution??'')}</p><p className="text-slate-600">{String(item.company??item.degree??item.level??item.issuer??'')}</p>{description&&<p className="mt-1 whitespace-pre-line leading-relaxed text-slate-700">{description}</p>}</div>})}</div>}</section>; }
