const base = import.meta.env.VITE_API_URL ?? 'http://localhost:4000/api';
const uid = import.meta.env.VITE_USER_ID as string | undefined;
const email = import.meta.env.VITE_USER_EMAIL as string | undefined;
export type ProfileRecord = { id: string; firstName: string|null; lastName: string|null; headline: string|null; summary: string|null; location: string|null; phone: string|null; website: string|null; yearsOfExperience: number|null; targetRoles: string[]; preferredLocations: string[]; remotePreference: string|null; experiences: Array<{id:string;company:string;title:string;startDate:string;endDate:string|null;description:string|null}>; educations: Array<{id:string;institution:string;degree:string;field:string|null;startDate:string;endDate:string|null}>; skills: Array<{id:string;name:string;level:string|null;technology:boolean}>; projects: Array<{id:string;name:string;description:string|null;url:string|null}>; certifications: Array<{id:string;name:string;issuer:string|null;issuedAt:string|null}>; achievements: Array<{id:string;title:string;description:string|null}> };
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { if (!uid) throw new Error('Set VITE_USER_ID to use profile persistence.'); const response = await fetch(`${base}${path}`, { ...init, headers: { 'Content-Type': 'application/json', 'x-user-id': uid, ...(email ? {'x-user-email': email} : {}), ...init.headers } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error ?? 'The request could not be completed.'); } return response.status === 204 ? (undefined as T) : response.json(); }
export const getProfile = () => request<{profile: ProfileRecord|null}>('/profile');
export const saveProfile = (body: unknown) => request<{profile: ProfileRecord}>('/profile', { method: 'PUT', body: JSON.stringify(body) });
export const createItem = (kind: string, body: unknown) => request<Record<string, unknown>>(`/profile/${kind}`, { method: 'POST', body: JSON.stringify(body) });
export const updateItem = (kind: string, id: string, body: unknown) => request<Record<string, unknown>>(`/profile/${kind}/${id}`, { method: 'PUT', body: JSON.stringify(body) });
export const deleteItem = (kind: string, id: string) => request<void>(`/profile/${kind}/${id}`, { method: 'DELETE' });
